# Generated by Django 6.0.2 on 2026-03-16 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CLASS_COORDINATOR', 'Class Coordinator'), ('YEAR_COORDINATOR', 'Year Coordinator'), ('HOD', 'HOD')], max_length=30)),
                ('program', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('section', models.CharField(blank=True, max_length=20, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
