# Generated by Django 6.0.2 on 2026-03-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('od', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odrequest',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
